INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('Mass Effect Trilogy', 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Trilogia épica de RPG e tiro com escolhas que afetam toda a galáxia.', 'O jogador assume o papel do Comandante Shepard em uma jornada contra a ameaça dos Reapers, unindo raças alienígenas e tomando decisões que moldam o destino do universo.', 4.8);

INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('Red Dead Redemption 2', 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Aventura épica no Velho Oeste com narrativa cinematográfica.', 'O jogador vive Arthur Morgan, membro da gangue Van der Linde, enfrentando dilemas morais, escolhas difíceis e a transformação do Velho Oeste no fim do século XIX.', 4.7);

INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('The Witcher 3: Wild Hunt', 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'RPG de mundo aberto premiado com narrativa madura e escolhas impactantes.', 'Geralt de Rívia embarca em uma jornada para encontrar sua filha adotiva Ciri, enquanto enfrenta monstros, reis e forças místicas em um mundo cheio de moralidade cinzenta.', 4.7);

INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('Sekiro: Shadows Die Twice', 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Ação desafiadora com ambientação no Japão feudal.', 'O jogador controla o lobo shinobi em busca de vingança contra samurais e seres míticos, dominando combate estratégico e exploração intensa em cenários belíssimos.', 4.7);

INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('Ghost of Tsushima', 2020, 'Role-playing (RPG), Adventure', 'Playstation', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Samurai contra invasão mongol em uma ilha devastada pela guerra.', 'Jin Sakai deve escolher entre honrar o código dos samurais ou adotar o caminho furtivo do Fantasma para salvar seu povo da invasão mongol em Tsushima.', 3.8);

INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('Super Mario World', 1990, 'Platform', 'Super NES', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Clássico do Super Nintendo com jogabilidade de plataforma icônica.', 'Mario e Luigi exploram Dinosaur Land para resgatar a Princesa Peach, enfrentando Bowser e seus lacaios em fases cheias de segredos e diversão atemporal.', 4.6);

INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('Hollow Knight', 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Metroidvania desafiador com atmosfera sombria e belíssima arte.', 'O jogador explora Hallownest, um reino subterrâneo repleto de mistérios, inimigos poderosos e segredos, em uma jornada de habilidade e descobertas.', 4.7);

INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('Ori and the Blind Forest', 2015, 'Platform', 'XBox, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Aventura emocionante com visuais deslumbrantes e trilha sonora marcante.', 'Ori, um espírito guardião, embarca em uma jornada com Naru para restaurar a floresta de Nibel, enfrentando desafios de plataforma e momentos emocionantes.', 4.6);

INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('Cuphead', 2017, 'Platform', 'XBox, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Jogo de ação com estética inspirada em desenhos animados dos anos 30.', 'Cuphead e Mugman enfrentam chefes desafiadores para pagar sua dívida com o Diabo, em um gameplay frenético com estilo artístico único e memorável.', 4.0);

INSERT INTO game (game_title, game_year, game_genre, game_plataform, game_image, game_short_description, game_long_description, game_score) VALUES ('Sonic CD', 1993, 'Platform', 'Sega CD', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Aventura clássica de Sonic com viagens no tempo.', 'Sonic enfrenta o maligno Dr. Robotnik para salvar Amy Rose e proteger o Little Planet, utilizando sua velocidade para viajar entre passado, presente e futuro.', 4.0);
